"""initial schema

Revision ID: 30646f7fa078
Revises: 
Create Date: 2026-08-15 01:25:14.843264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '30646f7fa078'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expedientes',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('estado_actual', sa.String(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(), nullable=False),
    sa.Column('cotizador_asignado', sa.String(), nullable=True),
    sa.Column('carga_antes', sa.Integer(), nullable=True),
    sa.Column('carga_despues', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('ingested_messages',
    sa.Column('message_hash', sa.String(), nullable=False),
    sa.Column('gmail_message_id', sa.String(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['expedientes.case_id'], ),
    sa.PrimaryKeyConstraint('message_hash')
    )
    op.create_table('state_transitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('estado_origen', sa.String(), nullable=True),
    sa.Column('estado_destino', sa.String(), nullable=False),
    sa.Column('evento', sa.String(), nullable=False),
    sa.Column('agente_actor', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['expedientes.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('state_transitions')
    op.drop_table('ingested_messages')
    op.drop_table('expedientes')
    # ### end Alembic commands ###
